DROP TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO;
DROP TABLE BUSINESS_INTELLIGENCE.TB_DM_CATEGORIA;
DROP TABLE BUSINESS_INTELLIGENCE.TB_DM_DATA;
DROP TABLE BUSINESS_INTELLIGENCE.TB_DM_LOCAL;
DROP TABLE BUSINESS_INTELLIGENCE.TB_DM_OFERTA;
DROP TABLE BUSINESS_INTELLIGENCE.TB_DM_POSICAO;
DROP TABLE BUSINESS_INTELLIGENCE.TB_DM_ESTABELECIMENTO;

CREATE TABLE BUSINESS_INTELLIGENCE.TB_DM_CATEGORIA(
   ID bigint PRIMARY KEY NOT NULL,
   CATEGORIA varchar(50),
   SUBCATEGORIA varchar(50)
);

CREATE TABLE BUSINESS_INTELLIGENCE.TB_DM_DATA(
   ID bigint PRIMARY KEY NOT NULL,
   ANO int,
   MES int,
   DIA int,
   HORA int,
   MINUTO int
);

CREATE TABLE BUSINESS_INTELLIGENCE.TB_DM_LOCAL(
   ID bigint PRIMARY KEY NOT NULL,
   PAIS varchar(3),
   ESTADO varchar(100),
   CIDADE varchar(150),
   BAIRRO varchar(150)
);

CREATE TABLE BUSINESS_INTELLIGENCE.TB_DM_OFERTA(
   ID bigint PRIMARY KEY NOT NULL,
   TIPO varchar(30),
   CATEGORIA varchar(50)
);

CREATE TABLE BUSINESS_INTELLIGENCE.TB_DM_ESTABELECIMENTO (
  ID bigint PRIMARY KEY NOT NULL,
  NOME_FANTASIA varchar(200),
  ID_ESTABELECIMENTO bigint
);

CREATE TABLE BUSINESS_INTELLIGENCE.TB_DM_POSICAO (
  ID bigint PRIMARY KEY NOT NULL,
  LATITUDE double,
  LONGITUDE double
);

CREATE TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO(
   ID bigint PRIMARY KEY NOT NULL,
   ID_DM_LOCAL bigint,
   ID_DM_DATA bigint,
   ID_DM_CATEGORIA bigint,
   ID_DM_OFERTA bigint,
   ID_DM_POSICAO bigint,
   ID_DM_ESTABELECIMENTO bigint,
   EMAIL varchar(255),
   NOME_COMPLETO varchar(255),
   ID_CLIENTE bigint,
   FLAG bit
);

ALTER TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO ADD CONSTRAINT FK_ID_DM_CATEGORIA FOREIGN KEY (ID_DM_CATEGORIA) REFERENCES BUSINESS_INTELLIGENCE.TB_DM_CATEGORIA(ID);
ALTER TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO ADD CONSTRAINT FK_ID_DM_DATA FOREIGN KEY (ID_DM_DATA) REFERENCES BUSINESS_INTELLIGENCE.TB_DM_DATA(ID);
ALTER TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO ADD CONSTRAINT FK_ID_DM_LOCAL FOREIGN KEY (ID_DM_LOCAL) REFERENCES BUSINESS_INTELLIGENCE.TB_DM_LOCAL(ID);
ALTER TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO ADD CONSTRAINT FK_ID_DM_OFERTA FOREIGN KEY (ID_DM_OFERTA) REFERENCES BUSINESS_INTELLIGENCE.TB_DM_OFERTA(ID);
ALTER TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO ADD CONSTRAINT FK_ID_DM_POSICAO FOREIGN KEY (ID_DM_POSICAO) REFERENCES BUSINESS_INTELLIGENCE.TB_DM_POSICAO(ID);
ALTER TABLE BUSINESS_INTELLIGENCE.TB_FATO_LOCALIZACAO ADD CONSTRAINT FK_ID_DM_ESTABELECIMENTO FOREIGN KEY (ID_DM_ESTABELECIMENTO) REFERENCES BUSINESS_INTELLIGENCE.TB_DM_ESTABELECIMENTO(ID);